### ISSUE TITLE
As a tutor, when I am looking at my observation sessions I want to be able to sort them to find the most relevant ones easily

### ISSUE THREAD

**Issue by unxpctederr** [catalyst/moodle-mod_observation#42]
This issue somewhat overlaps with #46 - perhaps this one only needs a search function
**Acceptance Criteria**

- [x] Given that I am a tutor, when I view the list of my assigned observation assessments, then I can sort them by nearest (datetime) first
- [x] Given that I am a tutor, when I view the list of observation assessments, then I can search for an observation assessment assigned to a specific student via a search box

**Comment by Gerrrrad** [comment]
The sorting function is already implemented. The sorting was turned on for all table headers except actions so the users can sort via all other table headers already.

Was moved to review back to in progress because I thought the search box was already implemented but that was to start an observation with the selected user.
